# Form implementation generated from reading ui file 'ui/champion.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_champion(object):
    def setupUi(self, champion):
        champion.setObjectName("champion")
        champion.resize(1000, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(champion)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = SubtitleLabel(parent=champion)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.teamname = SubtitleLabel(parent=champion)
        self.teamname.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.teamname.setObjectName("teamname")
        self.verticalLayout.addWidget(self.teamname)
        self.combobox = ComboBox(parent=champion)
        self.combobox.setObjectName("combobox")
        self.verticalLayout.addWidget(self.combobox)
        self.teamup = PrimaryPushButton(parent=champion)
        self.teamup.setObjectName("teamup")
        self.verticalLayout.addWidget(self.teamup)
        self.label_2 = BodyLabel(parent=champion)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.player_6 = ComboBox(parent=champion)
        self.player_6.setObjectName("player_6")
        self.gridLayout.addWidget(self.player_6, 1, 2, 1, 1)
        self.player_4 = ComboBox(parent=champion)
        self.player_4.setObjectName("player_4")
        self.gridLayout.addWidget(self.player_4, 1, 0, 1, 1)
        self.player = ComboBox(parent=champion)
        self.player.setObjectName("player")
        self.gridLayout.addWidget(self.player, 0, 0, 1, 1)
        self.player_3 = ComboBox(parent=champion)
        self.player_3.setObjectName("player_3")
        self.gridLayout.addWidget(self.player_3, 0, 2, 1, 1)
        self.player_5 = ComboBox(parent=champion)
        self.player_5.setObjectName("player_5")
        self.gridLayout.addWidget(self.player_5, 1, 1, 1, 1)
        self.player_2 = ComboBox(parent=champion)
        self.player_2.setObjectName("player_2")
        self.gridLayout.addWidget(self.player_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(champion)
        QtCore.QMetaObject.connectSlotsByName(champion)

    def retranslateUi(self, champion):
        _translate = QtCore.QCoreApplication.translate
        champion.setWindowTitle(_translate("champion", "冠军"))
        self.label.setText(_translate("champion", "冠军"))
        self.teamname.setText(_translate("champion", "当前无战队上场"))
        self.teamup.setText(_translate("champion", "上场"))
        self.teamup.setIcon(FIF.UP)
        self.label_2.setText(_translate("champion", "展示战队成员"))

from qfluentwidgets import FluentIcon as FIF
from qfluentwidgets import BodyLabel, ComboBox, PrimaryPushButton, SubtitleLabel
