# Form implementation generated from reading ui file 'ui/frame.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from function import get_resource_path


class Ui_frame(object):
    def setupUi(self, frame):
        frame.setObjectName("frame")
        frame.resize(1000, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        self.framelist = ListWidget(parent=frame)
        self.framelist.setMinimumSize(QtCore.QSize(160, 0))
        self.framelist.setObjectName("framelist")
        self.gridLayout.addWidget(self.framelist, 2, 1, 1, 1)
        self.now_framename = BodyLabel(parent=frame)
        self.now_framename.setObjectName("now_framename")
        self.gridLayout.addWidget(self.now_framename, 1, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.label = SubtitleLabel(parent=frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = SubtitleLabel(parent=frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.upButton = PrimaryPushButton(parent=frame)
        self.upButton.setMinimumSize(QtCore.QSize(100, 0))
        self.upButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 2, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.frame_pic = ImageLabel(parent=frame)
        self.frame_pic.setMaximumSize(QtCore.QSize(100, 100))
        self.frame_pic.setText("")
        self.frame_pic.setScaledContents(True)
        self.frame_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.frame_pic.setBorderRadius(14,14,14,14)
        self.frame_pic.setObjectName("frame_pic")
        self.verticalLayout.addWidget(self.frame_pic)
        self.status = BodyLabel(parent=frame)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.toggle_reason = BodyLabel(parent=frame)
        self.toggle_reason.setObjectName("toggle_reason")
        self.verticalLayout.addWidget(self.toggle_reason)
        self.toggle_time = BodyLabel(parent=frame)
        self.toggle_time.setObjectName("toggle_time")
        self.verticalLayout.addWidget(self.toggle_time)
        self.refresh_time = BodyLabel(parent=frame)
        self.refresh_time.setObjectName("refresh_time")
        self.verticalLayout.addWidget(self.refresh_time)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout, 2, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)

        self.retranslateUi(frame)
        QtCore.QMetaObject.connectSlotsByName(frame)

    def updatePixmap(self):
        # 获取当前窗口的高度
        window_height = self.window().height()
        # 获取当前窗口的宽度
        window_width = self.window().width()

        # 计算新的宽度，即窗口宽度的三分之一
        new_width = window_width // 2
        # 计算新的高度，即窗口高度的一半
        new_height = window_height // 3

        if new_width * 1.5 > new_height:
            self.frame_pic.scaledToWidth(new_width)
        else:
            # 按比例缩放到指定高度
            self.frame_pic.scaledToHeight(new_height)

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self.updatePixmap()

    def retranslateUi(self, frame):
        _translate = QtCore.QCoreApplication.translate
        frame.setWindowTitle(_translate("frame", "画面切换"))
        self.label.setText(_translate("frame", "选择画面"))
        self.label_2.setText(_translate("frame", "当前画面"))
        self.now_framename.setText(_translate("frame", "name"))
        self.upButton.setText(_translate("frame", "注入"))
        self.upButton.setIcon(FIF.RIGHT_ARROW)
        self.status.setText(_translate("frame", "切换状态：正在初始化")) #正在初始化、初始化成功、正在切换、切换成功
        self.frame_pic.setPixmap(QtGui.QPixmap(get_resource_path("data/frametest.jpg")))
        self.updatePixmap()
        self.status.setText(_translate("frame", "切换状态：初始化成功"))
        self.toggle_reason.setText(_translate("frame", "上次切换原因：初始化")) #用户手动注入、倒计时归零自动切换、初始化
        self.toggle_time.setText((_translate("frame", "上次切换时间：") + "-"))
        self.refresh_time.setText((_translate("frame", "上次刷新时间：") + "-"))
        terms = [
            '赛前倒计时', '成员介绍', "战队数据展示", "比分板和地图BP",
            '角色BP', '赛前等待', "加载动画", "赛中素材（绿幕）",
            "赛后数据", "冠军画面"
        ]

        # 添加列表项
        for term in terms:
            self.framelist.addItem(term)
from qfluentwidgets import BodyLabel, ImageLabel, ListWidget, PrimaryPushButton, SubtitleLabel
from qfluentwidgets import FluentIcon as FIF